### ISSUE TITLE
Exit the process when there are errors pulling messages from PubSub

### ISSUE THREAD

**Issue by Draiken** [replaygaming/go-metrics#10]
Currently when we have errors with PubSub, we just log a message showing the error. The problem is that sometimes PubSub does not recover, meaning that the Go-Metrics is still running but not really working.
When we have an unrecoverable error from PubSub, it's better if we error out, and let a system like Kubernetes, restart the process.

**DoD**
- [x] Process exits on PubSub errors
- [x] Documentation created/updated
- Ready to be deployed
- Reviewed by at least one person

**Comment by pranavcode** [comment]
Considering the current state of go-metrics app, rewriting of some parts of that system to reflect updated go packages, restructuring and some scenarios that need to be tested, I would suggest renegotiating the size estimation on this card. I feel its complexity is more towards Medium range.

**Comment by pranavcode** [comment]
Most of my initial time was spent making the whole system work together locally to make sure I am able to reproduce the go-metrics app getting stuck scenarios. I am successfully testing those scenarios now and fixing them one at a time.

**Comment by Draiken** [comment]
Hmm, I'd argue this story as the title current states, is a small one.
Don't you think if you need to do more things outside of exiting when there is an error pulling messages, you should have another story for it?

Right now I'm a bit on the dark here. Looking from outside it's a simple change from `log.Printf` to `log.Fatalf`

**Comment by Draiken** [comment]
Actually, we already exit with `Fatal` if the messages are not pulled... so what exactly is being done here? :stuck_out_tongue:

**Comment by pranavcode** [comment]
The process does exit with Fatal, on cases where the process does not find subscriptions, topics, etc, things related to config. But, when the process on go-metrics encounters either unreachable pubsub or pubsub disconnection from other end, the process stays up and does no work. I am working on making sure the process exits by itself so it could be restarted, as it wont connect to pubsub, even when pubsub comes back.

**Comment by pranavcode** [comment]
For better context on scenarios, adding a note here:
```
1. Go-metrics app is connected to PubSub, PubSub dies, Go-metrics detect the disconnection and retries connecting forever, connects when PubSub is available [InPlace]
2. Go-metrics cannot connect to PubSub, Go-metrics detect the disconnection and retries connecting forever, connects when PubSub is available [InPlace]
3. Go-metrics is connected to PubSub, Go-metrics disconnects, PubSub disconnects, Go-metrics tries to reconnect and connects when PubSub is available [InPlace]
4. Go-metrics is connected to pubsub, PubSub is not listening any more, Go-metrics app is stuck (exit and restart go-metrics) [InProgress]
5. Go-metrics tries connecting to PubSub, PubSub is not receiving any connections, Go-metrics app is stuck (exit and restart go-metrics) [InProgress]```

**Comment by pranavcode** [comment]
While testing this on staging, post review, found few changes that needs to be done as part of this story, without which we cannot deploy this. So, moving back to `in progress`, as i am currently working on those updates.

**Comment by pranavcode** [comment]
All the changes are in place, tested against emulator and staging, and ready for release. We will need to merge the PR on consumer code first and ask glide on metrics to fetch master from consumer repo, instead of current PR branch

**Comment by Draiken** [comment]
Then just do it :tm: ! :slightly_smiling_face:

**Comment by pranavcode** [comment]
This is done for now and ready for deploy, but I want to do a quick round of checks once again when we have staging redis/sidekiq stable. Won't delay longer, should be quick.
