### ISSUE TITLE
Ensure failed events are retried

### ISSUE THREAD

**Issue by Draiken** [replaygaming/go-metrics#11]
We can't expect all the HTTP requests made to Amplitude work. Because of that we need to ensure all requests are retried on error events.

**DoD**
- [ ] Process exits on errors processing them through Amplitude
- [ ] Documentation created/updated
- Ready to be deployed
- Reviewed by at least one person

**Comment by pranavcode** [comment]
Renaming the issue as it is related to events/messages in enqueued in PubSub to be processed and sent to Amplitude.

**Comment by pranavcode** [comment]
As per the primary discussion with Felipe, we have thought about managing the failed events by creating a special golang channel that will have all the events that errored out during their processing and needs reprocessing. This error channel will feed these events back into original PubSub queue, to be processed eventually.

Currently, we only consume messages from PubSub and acknowledge them from go-metrics. Now, we will be sending messages on PubSub queue, making this a bidirectional communication.

**Comment by pranavcode** [comment]
Moving back to ready. Its dependent on https://github.com/replaygaming/go-metrics/issues/10, which is still in progress.

**Comment by pranavcode** [comment]
Updating the issue to say errors on Amplitude instead of pubsub.

**Comment by pranavcode** [comment]
Picking this up as its dependent story has been done and this is unblocked.

**Comment by Draiken** [comment]
No longer going to be used
