### ISSUE TITLE
Investigate events ack process during error scenarios

### ISSUE THREAD

**Issue by pranavcode** [replaygaming/go-metrics#9]
It is observed that if there is an error during processing of an event in Metrics Go app, the respective event is lost.

DoD:
- [x] Investigate the issue by duplicating it on local env
- [x] Create a story to fix that issue if required

**Comment by Draiken** [comment]
As I said when we talked, we should remove this service altogether in favor of using Amplitude's Ruby SDK and sending the events through sidekiq.

**Comment by pranavcode** [comment]
Writing this for the record.
After taking a look into Ruby SDK support from Amplitude, unfortunately, I found there is no Ruby SDK from Amplitude. They recommend using analytics aggregation service Segment to track events from Ruby code using Segment's SDK. Segment is a paid service and it's not commercially viable for us. Also, we will need to convert all the events tracked to using Segment API.
Considering the cost to do so and overall value it delivers to us, I and Felipe, after discussing the pros and cons, decided to continue using Go Metrics App. So, we will not be removing the service for now, but instead, repair it to fix the existing issues.

**Comment by pranavcode** [comment]
Closing this as Felipe and I are creating stories to tackle different parts of the metrics that are either broken, incomplete or inaccurate.
